config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  root :to => "users#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'users/sessions#new', :as => :new_users_session
    match 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session, :via => [:get, :delete]
  end
  
  resources :works do
    resources :likes, :comments
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :journals
  resources :books
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to works#index, needs to be defined.
  resources :users, :path => "/"

end

app/models/work.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

require 'bibtex'

class Work < ActiveRecord::Base
  @queue = :works
  
  has_many :retrievals, :dependent => :destroy, :order => "retrievals.source_id"
  has_many :sources, :through => :retrievals 
  has_many :citations, :through => :retrievals
  has_many :users, :through => :contributors
  has_many :contributors, :order => :position, :dependent => :destroy
  has_many :likes
  has_many :likers, :class_name => 'User', :source => 'user', :through => :likes
  has_many :comments
  has_many :commenters, :class_name => 'User', :source => 'user', :through => :comments
  
  validates :url, :title, :type, :presence => true
  validates :url, :uniqueness => true
  
  attr_accessible :first_page, :title, :short_doi, :volume, :last_page, :year, :journal_id, :issue, :book_id, :doi, :type, :url, :mas

  after_create :create_retrievals

  scope :query, lambda { |query|
    { :conditions => [ "doi like ?", "%#{query}%" ] }
  }
  
  scope :cited, lambda { |cited|
    case cited
    when '1', 1
      { :include => :retrievals,
        :conditions => "retrievals.citations_count > 0 OR retrievals.other_citations_count > 0" }
    when '0', 0
      { :conditions => 'EXISTS (SELECT * from retrievals where work_id = `works`.id GROUP BY work_id HAVING SUM(IFNULL(retrievals.citations_count,0)) + SUM(IFNULL(retrievals.other_citations_count,0)) = 0)' }
      #works.id IN (SELECT works.id FROM works LEFT OUTER JOIN retrievals ON retrievals.work_id = works.id GROUP BY works.id HAVING IFNULL(SUM(retrievals.citations_count) + SUM(retrievals.other_citations_count), 0) = 0)' }
    else
      {}
    end
  }

  scope :limit, lambda { |limit| (limit && limit > 0) ? {:limit => limit} : {} }

  scope :order, lambda { |order|
    if order == 'published_on'
      { :order => 'published_on' }
    else
      {}
    end
  }

  scope :stale_and_published,
    :conditions => ["works.id IN (
	SELECT DISTINCT work_id
	FROM retrievals 
	JOIN sources ON retrievals.source_id = sources.id 
	WHERE retrievals.work_id = works.id 
	AND retrievals.retrieved_at < TIMESTAMPADD(SECOND, - sources.staleness, UTC_TIMESTAMP())
	AND sources.active = 1
	AND (
		sources.disable_until IS NULL 
		OR sources.disable_until < UTC_TIMESTAMP()))
	AND works.published_on < ?", Date.today],
    :order => "retrievals.retrieved_at",
    :include => :retrievals

  default_scope :order => "IF(works.published_on IS NULL, works.year, works.published_on) desc"

  def to_param
    DOI.to_uri(doi)
  end

  def doi=(new_doi)
    self[:doi] = DOI.from_uri(new_doi)
  end

  def stale?
    new_record? or retrievals.empty? or retrievals.active_sources.any?(&:stale?)
  end

  def refreshed!
    self.retrieved_at = Time.now
    self
  end
  
  #Get citation count by category and sources from the activerecord data
  def citations_by_category
    results = {}
    
    for ret in retrievals
      # Only get citations for active sources
      if ret.source.active
        if results[ret.source.category_id] == nil then
          results[ret.source.category_id] = {
            :name => ret.source.category && ret.source.category.name.downcase,
            :total => ret.citations_count + ret.other_citations_count,
            :sources => []
          }
          results[ret.source.category_id][:sources] << {
            :name => ret.source.name,
            :total => ret.citations_count + ret.other_citations_count,
            :public_url => ret.source.public_url(ret)
          }
        else
          results[ret.source.category_id][:total] = results[ret.source.category_id][:total] + ret.citations_count + ret.other_citations_count
          results[ret.source.category_id][:sources] << {
            :name => ret.source.name,
            :total => ret.citations_count + ret.other_citations_count,
            :public_url => ret.source.public_url(ret)
          }
        end
      end
    end
    
    categoriesCount = []
    
    results.each do | key, value |
      categoriesCount << value
    end
    
    categoriesCount
  end
  
  #Get citation count by source from the activerecord data
  def citations_by_source(source)
    
    return nil unless source.active
    ret = self.retrievals.by_source(source.id).first
    return if ret.nil?
    
    result = {
          :total => ret.citations_count + ret.other_citations_count,
          :public_url => ret.source.public_url(ret)
        }
    result
  end
  
  #Get cites for the given source from the activeRecord data
  def get_cites_by_category(categoryname)
    categoryname = categoryname.downcase
    retrievals.map do |ret|
      if ret.source.category.name.downcase == categoryname && (ret.citations_count + ret.other_citations_count) > 0
        #Cast this to an array to get around a ruby 'singularize' bug
        { :name => ret.source.name.downcase, :citations => ret.citations.to_a }
      end
    end.compact
  end
  
  def citations_count(categoryname = nil)
    if categoryname.nil?
      retrievals.inject(0) {|sum, r| sum + r.total_citations_count }
    else
      categoryname = categoryname.downcase
      retrievals.inject(0) do |result, ret|
        if ret.source.category.name.downcase == categoryname
          if ret.source.category.add_sources
            result = result + ret.total_citations_count 
          else
            result = ret.total_citations_count > result ? ret.total_citations_count : result
          end
        end
        result
      end
    end
    
    # retrievals.sum(:citations_count) + retrievals.sum(:other_citations_count)
  end

  def cited_retrievals_count
    retrievals.select {|r| r.total_citations_count > 0 }.size
  end

  def to_xml(options = {})
    options[:indent] ||= 2
    sources = (options.delete(:source) || '').downcase.split(',')
    xml = options[:builder] ||= ::Builder::XmlMarkup.new(:indent => options[:indent])
    xml.instruct! unless options[:skip_instruct]
    xml.tag!("work", :doi => doi, :title => title, :citations_count => citations_count,:pub_med => pub_med,:pub_med_central => pub_med_central, :updated_at => retrieved_at, :published => (published_on.blank? ? nil : published_on.to_time)) do
      if options[:citations] or options[:history]
        retrieval_options = options.merge!(:dasherize => false, 
                                           :skip_instruct => true)
        retrievals.each do |r| 
          r.to_xml(retrieval_options) \
            if (sources.empty? or sources.include?(r.source['type'].downcase))
               #If the result set is emtpy, lets not return any information about the source at all
               #\
               #and (r.total_citations_count > 0)
        end
      end
    end
  end

  def explain
    msgs = ["[#{id}]: #{doi} #{retrieved_at}#{" stale" if stale?}"]
    retrievals.each {|r| msgs << "  [#{r.id}] #{r.source.name} #{r.retrieved_at}#{" stale" if r.stale?}"}
    msgs.join("\n")
  end

  def to_json(options={})
    result = { 
      :work => { 
        :doi => doi, 
        :shortdoi => "10/" + short_doi,
        :title => title, 
        :year => year,
        :pub_med => pub_med,
        :pub_med_central => pub_med_central,
        :mas => mas,
        :mendeley => mendeley,
        :citations_count => citations_count,
        :published => (published_on.blank? ? nil : published_on.to_time),
        :updated_at => retrieved_at
      }
    }
    sources = (options.delete(:source) || '').downcase.split(',')
    if options[:citations] or options[:history]
      result[:work][:source] = retrievals.map do |r|
        r.to_included_json(options) \
          if (sources.empty? or sources.include?(r.source.class.to_s.downcase))
             #If the result set is empty, lets not return any information about the source at all
             #\
             #and (r.total_citations_count > 0)
      end.compact
    end
    result.to_json(options)
  end
  
  def to_bib
    # Define BibTeX citation
    case type
    when "JournalArticle"
      bib_entry = BibTeX::Entry.new({
         :type => "work",
         :title => title,
         :user => contributors_with_names,
         :doi => doi,
         :url => "http://doi.org/" + short_doi,
         :journal => journal ? journal.title : ""})
      bib_entry.add(:year => year) unless year.blank?
      bib_entry.add(:volume => volume) unless volume.blank?
      bib_entry.add(:number => issue) unless issue.blank?
      bib_entry.add(:pages => pages) unless pages.blank?
    when "BookContent"
      bib_entry = BibTeX::Entry.new({
         :type => "incollection",
         :title => title,
         :user => contributors_with_names,
         :doi => doi,
         :url => "http://doi.org/" + short_doi,
         :publisher => "",
         :booktitle => book ? book.title : ""})
      bib_entry.add(:year => year) unless year.blank?
      bib_entry.add(:volume => volume) unless volume.blank?
      bib_entry.add(:number => issue) unless issue.blank?
      bib_entry.add(:pages => pages) unless pages.blank?
    when "conference_paper"
      bib_entry = BibTeX::Entry.new({
         :type => "inproceedings",
         :title => title,
         :user => contributors_with_names,
         :doi => doi,
         :url => "http://doi.org/" + short_doi,
         :booktitle => book ? book.title : ""})
      bib_entry.add(:year => year) unless year.blank?

app/models/works/book_content.rb
class BookContent < Work
  belongs_to :book
  has_many :contributors, :foreign_key => :work_id
end

app/models/works/book_series.rb
class BookSeries < Work
  
end

app/models/works/component.rb
class Component < Work
  
end

app/models/works/conference_paper.rb
class ConferencePaper < Work
  belongs_to :book
  has_many :contributors, :foreign_key => :work_id
end

app/models/works/journal_article.rb
class JournalArticle < Work
  belongs_to :journal
  has_many :contributors, :foreign_key => :work_id
  
  validates :doi, :format => { :with => DOI::FORMAT }
  validates :doi, :uniqueness => true
  validates :journal_id, :presence => true
end

app/models/works/journal_issue.rb
class JournalIssue < Work
  
end

app/controllers/works_controller.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class WorksController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show ]
  before_filter :load_work, 
                :only => [ :edit, :update, :destroy ]
  
  def index
    redirect_to users_path
  end

  # GET /works/1
  # GET /works/1.xml
  def show
    load_work #load_work(eager_includes)
    
    if params[:refresh] == "now"
      Retriever.new(:lazy => false, :only_source => false).delay.update(@work)        
    end

    format_options = params.slice :citations, :history, :source

    if params[:refresh] == "soon" or @work.stale?
      #uid = RetrievalWorker.async_retrieval(:work_id => @work.id)
      #logger.info "Queuing work #{@work.id} for retrieval as #{uid}"
    end
    
    respond_to do |format|
      format.html # show.html.erb
      format.mobile # show.mobile.erb
      format.js { render :show }
      format.xml do
        response.headers['Content-Disposition'] = 'attachment; filename=' + params[:id].sub(/^info:/,'') + '.xml'
        render :xml => @work.to_xml(format_options)
      end
      format.csv  { render :csv => @work }
      format.json { render :json => @work.to_json(format_options), :callback => params[:callback] }
      format.bib { render :bib => @work }
      format.ris { render :ris => @work }
    end
  end

  # GET /works/new
  # GET /works/new.xml
  def new
    @work = Work.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @work }
      format.json { render :json => @work }
    end
  end

  # POST /works
  # POST /works.xml
  def create
    # Set type to "Other" if no type is provided
    params[:work][:type] ||= "Other"
    
    @work = Work.new(params[:work])

    respond_to do |format|
      if @work.save
        flash[:notice] = 'Work was successfully created.'

        Source.all.each do |source|
          Retrieval.find_or_create_by_work_id_and_source_id(@work.id, source.id)
        end    

        format.html { redirect_to(@work) }
        format.xml  { render :xml => @work, :status => :created, :location => @work }
        format.json { render :json => @work, :status => :created, :location => @work }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
        format.json { render :json => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
    
  end
  
  # PUT /works/1
  # PUT /works/1.xml
  def update
    respond_to do |format|
      if @work.update_attributes(params[:work])
        flash[:notice] = 'Work was successfully updated.'
        format.html { redirect_to(@work) }
        format.xml  { head :ok }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @work.errors, :status => :unprocessable_entity }
        format.json { render :json => @work.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.xml
  def destroy
    @work.destroy

    respond_to do |format|
      format.html { redirect_to(works_url) }
      format.xml  { head :ok }
      format.json { head :ok }
    end
  end

protected
  def load_work(options={})
    # Load one work given query params, for the non-#index actions
    @work = Work.find(params[:id])
  end

  def eager_includes
    returning :include => { :retrievals => [ :source ] } do |r|
      r[:include][:retrievals] << :citations if params[:citations] == "1"
      r[:include][:retrievals] << :histories if params[:history] == "1"
      r[:conditions] = ['LOWER(sources.type) IN (?)', params[:source].downcase.split(",")] if params[:source]
    end
  end
end

app/helpers/works_helper.rb
# $HeadURL$
# $Id$
#
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

module WorksHelper
end

app/views/works/_comment.html.erb
<p><%= formatted_citation(@work).html_safe %>.
<br />
<% unless @work.published_on.blank? %>
	<%= time_ago_in_words(@work.published_on) + " ago" + (user_signed_in? ? " - " : "") %>
<% end %>
<% unless @work.doi.blank? %>
  <%= link_to "http://dx.doi.org/" + @work.doi, "http://dx.doi.org/" + @work.doi, :itemprop => "url" %>
<% end %>
<br />
<% if user_signed_in? %>
  <%= link_to "Comment", new_work_comment_path(@work.id), :remote => :true %> - 
  <% unless @work.likers.include?(current_user) %>
    <%= link_to "Like", work_likes_path(@work.id), :method => :post, :remote => :true %> -
  <% end %> 
<% end %>
<%= link_to "Share on Mendeley", "http://www.mendeley.com/import/?url=" + @work.url, :target => "_blank" %> - 
<%= link_to "Share on CiteULike", "http://www.citeulike.org/posturl?url=" + @work.url + "&title=" + @work.title, :target => "_blank" %>
<br /><span class="label"><%= @work.type.underscore.humanize %></span>
<% active_categories.each do |category| %>
  <% if @work.citations_count(category.name) > 0 %>
    <span class="label label-<%= category.name.downcase %>"><%= pluralize(@work.citations_count(category.name), category.name.singularize) %></span>
  <% end %>
<% end %>
</p>
<% unless @work.likes.empty? %>
  <p><i class="icon-star"></i> 
  <% @work.likers.each do |liker| %>
	  <%= link_to liker.name, user_path(liker.username) %>
  <% end.to_sentence %> liked this 
  <% if user_signed_in? and @work.likers.include?(current_user) %>
    <% like = @work.likes.detect { |l| l.user_id == current_user.id } %>
    <%= link_to " (Un-like)", work_like_path(@work.id, like.id), :method => :delete, :remote => :true %>
  <% end %></p>
<% end %>
<% unless @work.comments.empty? %>
	<p>
  <% @work.comments.each do |comment| %>
	  <% if controller.action_name == "edit" and comment.id == @comment.id %>
	 		<%= form_for(@comment, :url => work_comment_url(@work.id, comment.id), :remote => true) do |form| %>
	      <%= form.hidden_field :user_id, :value => current_user.id %>
        <div class="input-prepend">
	        <span class="add-on"><i class="icon-comment"></i></span>
		      <%= form.text_field :text, :class => "span7" %>
		    </div>
        <%= form.submit("Submit", :class => "btn-primary btn-mini") %> <%= link_to "Cancel", work_comments_path(@work.id), :remote => true %>
      <% end %>
    <% else %>
	    <%= comment.text %> - <%= link_to comment.user.name, user_path(comment.user.username) %>
	    <% if comment.user == current_user %>
	      ( <%= link_to "edit", edit_work_comment_path(@work.id, comment.id), :remote => true %> | <%= link_to "delete", work_comment_path(@work.id, comment.id), :method => :delete, :remote => true %> )
      <% end %>
      <br />
	  <% end %>
  <% end %>
  </p>
<% end %>
<% if controller.action_name == "new" %>
  <%= form_for(@comment, :url => work_comments_url(@work.id), :remote => true) do |form| %>
    <%= form.hidden_field :user_id, :value => current_user.id %>
    <div class="input-prepend">
      <span class="add-on"><i class="icon-comment"></i></span>
      <%= form.text_field :text, :class => "span7" %>
    </div>
    <%= form.submit("Submit", :class => "btn-primary btn-mini") %> <%= link_to "Cancel", work_comments_path(@work.id), :remote => true %>
  <% end %>
<% end %>

app/views/works/_form.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% work ||= form %>
<%= form_for(work.id) do |f| %>
  <p>
    <%= f.label :doi, "DOI" %><br />
    <%= f.text_field :doi %>
  </p>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :published_on %><br />
    <%= date_select 'work', 'published_on', :order => [:month, :day, :year] %>
  </p>
  <p>
    <%= f.submit(work.new_record? ? "Create" : "Update") %>
  </p>
<% end %>

app/views/works/_index.html.erb
<div class="content">
	<div class="page-header">
    <h2>Works</h2>
  </div>
	
  <% unless @works.empty? %>
		<% @works.each do |@work| %>
			<div class="row" id="work_<%= @work.id %>">
				<%= render :partial => "works/work" %>
		  </div>
    <% end %>	
		<%= will_paginate @works, :params => { :controller => :works, :authenticity_token => nil } %>
  <% else %>
    <div class="alert alert-info">
      No works found.
	  </div>
  <% end %>
</div>

app/views/works/_show.html.erb
<div class="content">
	<div class="page-header">
    <h2><%= @work.title %></h2>
  </div>

	<div class="row">
	  <div class="span8">
			<div itemscope itemtype="http://schema.org/ScholarlyArticle">
				<div id="comment_<%= @work.id %>">
					<%= render :partial => "works/comment" %>
			  </div>
	    </div>
	  </div>

	  <div class="span3 offset1">
		  <p><%= link_to "JSON", work_path(@work.id, :format => :json) %> | <%= link_to "XML", work_path(@work.id, :format => :xml) %> | <%= link_to "BibTeX", work_path(@work.id, :format => :bib) %> | <%= link_to "RIS", work_path(@work.id, :format => :ris) %> | <%= link_to "CSV", work_path(@work.id, :format => :csv) %></p>
	  </div>
  </div>
	
	<ul class="nav nav-tabs">
		<li class="active"><a href="#source" data-toggle="tab">Metrics</a></li>
	</ul>
	
	<div class="tab-content">		
    <% if @work.citations_count > 0 %>
		  <div class="tab-pane active" id="source">
	      <%= render :partial => 'source'%>
	    </div>
    <% end %>
  </div>
</div>

app/views/works/_source.html.erb
<% active_categories.each do |category| %>
  <% unless @work.get_cites_by_category(category.name).blank? %>
		<h3><%= h(category.name) %> <small><%= h(category.work_description) %></small></h3>
	 
		<ul class="thumbnails">    
			<% category.sources.active.each do |source| %>
			  <% if @work.citations_by_source(source)[:total] > 0 %>
			    <li class="span3">
				    <div class="thumbnail">
					    <%= image_tag source.class.to_s.downcase + ".gif" %>
					    <div class="count">
							<% if @work.citations_by_source(source) and @work.citations_by_source(source)[:public_url] and @work.citations_by_source(source)[:total] > 0 %>
		            <%= link_to h(@work.citations_by_source(source)[:total]), @work.citations_by_source(source)[:public_url] %>
		          <% else %>
		            <%= @work.citations_by_source(source) ? @work.citations_by_source(source)[:total] : 0 %>
		          <% end %>
		          </div>
					  </div>
					</li>
			  <% end %>
			<% end %>
		</ul>
	<% end %>
<% end %>

app/views/works/_work.html.erb
<% unless @work.users.empty? %>
  <div class="span1">
  	<% @work.users.each do |user| %>
      <% if @user.nil? or @user.id != user.id %>
		    <%= link_to image_tag("http://api.twitter.com/1/users/profile_image/#{user.username}", :class => "photo_works"), user_path(user.username) %>
		  <% end %>
		  <%= "&nbsp;".html_safe if @user and [@user] == @work.users %>
		<% end %>
	</div>
	<div class="span8 work">
<% else %>
  <div class="span8 offset1 work">
<% end %>
    <div itemscope itemtype="http://schema.org/ScholarlyArticle">
	    <h4><%= link_to @work.title, work_path(@work.id) %></h4>
		  <div id="comment_<%= @work.id %>">
			  <%= render :partial => "works/comment" %>
	    </div>
    </div>
  </div>

app/views/works/comment.js.erb
$("#comment_<%= @work.id %>").html("<%= escape_javascript(render "works/comment", :locals => { :work => @work }) %>");

app/views/works/edit.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
  <h1>Editing work <%=h @work.doi %></h1>

  <%= render :partial => "form", :object => @work %>

  <%= link_to 'Show', @work %>
  <br/>
  <%= link_to 'Back to list', works_path %>
</div>
</div>

app/views/works/index.mobile.erb
<div data-role="header">
	<%= link_to 'Users', users_path, "data-role" => "button", "data-icon" => "home", "data-transition" => "reverse slide" %>
	<h1>Works</h1>
	<%= link_to 'About', about_path, "data-role" => "button", "data-icon" => "info" %>
</div>

<div data-role="content">
	<%= form_tag works_path, :method => :get, :remote => false, :class => "ui-listview-filter ui-bar-c", "data-ajax" => "true", "data-transition" => "none", :role => "search" do %>
    <input name="q" value="<%= params[:q] %>" placeholder="Filter works..." data-type="search" class="ui-input-text ui-body-c"/>
  <% end %>
	<ul data-role="listview" data-theme="c">
    <% @works.each do |work| %>
	    <li><a href="<%= work_path(work.id) %>" class="normal">
        <h3><%= work.title %></h3>
        <%= formatted_citation(work, :without_links => true).html_safe %>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/works/new.html.erb
<%#
  # $HeadURL$
  # $Id$
  #
  # Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
  # http://www.plos.org/
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
  <h1>Add a new work</h1>

  <%= render :partial => "form", :object => @work %>

  <%= link_to 'Back to list', works_path %>
</div>
</div>

app/views/works/show.js.erb
$('#show').html("<%= escape_javascript(render "show") %>");