config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  root :to => "users#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'users/sessions#new', :as => :new_users_session
    match 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session, :via => [:get, :delete]
  end
  
  resources :works do
    resources :likes, :comments
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :journals
  resources :books
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to works#index, needs to be defined.
  resources :users, :path => "/"

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  
  def twitter
    @user = User.find_for_twitter_oauth(env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', :kind => 'Twitter'
      @user.remember_me = true
      sign_in_and_redirect @user, :event => :authentication
    else
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.failure', :kind => 'Twitter'
      redirect_to root_path
    end
  end
  
  def google
    raise request.env["omniauth.auth"].to_yaml
  end

  def oauth_mendeley
    raise request.env["omniauth.auth"].to_yaml
  end
  
  def passthru
    render :file => "#{Rails.root}/public/404.html", :status => 404, :layout => false
  end
  
  protected

  # This is necessary since Rails 3.0.4
  # See https://github.com/intridea/omniauth/issues/185
  # and http://www.arailsdemo.com/posts/44
  def handle_unverified_request
    true
  end
  
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  def index
  end
  
  def new
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# Copyright (c) 2011 Martin Fenner
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [ :index, :show ]
  before_filter :load_user, 
                :only => [ :edit, :update, :destroy ]

  # GET /users
  # GET /users.xml
  
  def index
   if !params[:q].blank?
     @works = Work.paginate :page => params[:page], 
       :per_page => 10,
       :include => :users,
       :conditions => ["users.name REGEXP ? or users.username REGEXP ? or users.native_name REGEXP ? or works.title REGEXP ? or works.doi REGEXP ?", params[:q], params[:q], params[:q], params[:q], params[:q]]
   else
     collection = Work
     collection = collection.cited(params[:cited])  if params[:cited]
     collection = collection.query(params[:query])  if params[:query]
     collection = collection.order(params[:order])  if params[:order]
     
     if user_signed_in?
       # Fetch all works by the users you are following
       @works = collection.paginate :conditions => ["FIND_IN_SET(contributors.user_id, '?')",current_user.friends], :include => [:users, :contributors], :page => params[:page], :per_page => 10
     else
       @works = collection.paginate :page => params[:page], :per_page => 10
     end
   end
   
   @source = Source.find_by_type(params[:source]) if params[:source]

   respond_to do |format|
     format.html do 
       if request.xhr?
         render :partial => "index" 
       end
     end
     format.mobile do 
       render :index if request.xhr?
     end
     format.xml  { render :xml => @works }
     format.json { render :json => @works, :callback => params[:callback] }
     format.csv  { render :csv => @works }
     format.rss { render :rss => @works }
     format.js
   end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    load_user
    
    if params[:refresh] == "now"
      Retriever.new(:lazy => false, :only_source => false).delay.update_works_by_user(@user)  
    end
        
    respond_to do |format|
      format.html do 
        if request.xhr?
          render :partial => params[:partial] 
        else
          
        end
      end
      format.js { render :show }
      format.mobile
      format.xml do
        response.headers['Content-Disposition'] = 'attachment; filename=' + params[:id].sub(/^info:/,'') + '.xml'
        render :xml => @user.works.to_xml
      end
      format.csv  { render :csv => @user }
      format.json { render :json => @user.to_json, :callback => params[:callback] }
      format.bib { render :bib => @user }
      format.ris { render :ris => @user }
      format.rss { render :rss => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
      format.json { render :json => @user }
    end
  end
  
  # GET /users/1/edit
  def edit    
    respond_to do |format|
      format.html { render :show }
      format.js { render :show }
    end
  end

  # POST /users
  # POST /users.xml
  def create
    # Get user if it exists, otherwise create new one
    #@user = User.find_or_initialize_by_mas(:mas  => params[:user][:mas])

    #respond_to do |format|
    #  if @user.save
    #    # Fetch user information and update user
    #    properties = User.fetch_properties(@user)
    #    @user = User.update_properties(@user, properties)
    #    flash[:notice] = 'User was successfully created.' if @user.new_record?
    
    #    format.html { redirect_to user_path(@user.mas, :format => :html) }
    #    format.xml  { render :xml => @user, :status => :created, :location => @user }
    #    format.json { render :json => @user, :status => :created, :location => @user }
    #  else
    #    format.html { render :action => "new" }
    #    format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
    #    format.json { render :json => @user.errors, :status => :unprocessable_entity }
    #  end
    #end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update  
    respond_to do |format|
      if @user.update_attributes(params[:user])
        if params[:service] == "mas"
          # First remove all mas work claims, e.g. because Microsoft Academic Search ID was changed or set to empty 
          @user.contributors.where(:service => "mas").each do |contributor|
            contributor.update_attributes(:user_id => nil)
          end
          
          # Get works from user, return nil if no response
          results = MicrosoftAcademicSearchService.get_works(@user)
          
          unless results.empty?
            results.each do |result|
              # Only add works with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                work = Work.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                work.save
                # Check that DOI is valid
                if work.valid?
                  work.update_attributes(:mas => result["ID"])
                  result["Author"].each do |user|
                    contributor = Contributor.find_or_create_by_work_id_and_mas_and_service(:work_id => work.id,
                                                            :mas => user["ID"],
                                                            :service => "mas",
                                                            :surname => user["LastName"],
                                                            :given_name => user["FirstName"]) 
                    contributor.update_attributes(:user_id => @user.id) if (user["ID"].to_s == @user.mas)
                  end
                  Work.delay.update_via_crossref(work)
                end
              end
            end
          end
        elsif params[:service] == "authorclaim"
          # First remove all authorclaim work claims, e.g. because AuthorClaim ID was changed or set to empty
          @user.contributors.where(:service => "authorclaim").each do |contributor|
            contributor.update_attributes(:user_id => nil)
          end
          
          # Fetch works from user, return nil if no response
          results = AuthorClaimService.get_works(@user)
          
          unless results.blank?
            results[:works].each do |result|
              # Only add works with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                work = Work.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                work.save
                # Check that DOI is valid
                if work.valid?
                  contributor = Contributor.create(:work_id => work.id,
                                                          :user_id => @user.id,
                                                          :surname => results[:contributor]["surname"],
                                                          :given_name => results[:contributor]["given_name"],
                                                          :service => "userclaim",
                                                          :userclaim => @user.userclaim)
                end
                Work.delay.update_via_crossref(work)
              end
            end
          end
        elsif params[:service] == "scopus"
          # First remove all scopus work claims, e.g. because Scopus Author ID was changed or set to empty 
          @user.contributors.where(:service => "scopus").each do |contributor|
            contributor.update_attributes(:user_id => nil)
          end

          # Fetch works from user, return nil if no response
          results = ScopusService.delay.get_works(@user)

          unless results.empty?
            results.each do |result|
              # Only add works with DOI and title
              unless result["DOI"].nil? or result["Title"].nil?
                #result["DOI"] = DOI::clean(result["DOI"])
                work = Work.find_or_create_by_doi(:doi => result["DOI"], :title => result["Title"])
                work.save
                # Check that DOI is valid
                if work.valid?
                  work.update_attributes(:scopus => result["ID"])
                  result["Author"].each do |user|
                    contributor = Contributor.find_or_create_by_work_id_and_scopus_and_service(:work_id => work.id,
                                                            :scopus => user["ID"],
                                                            :service => "scopus",
                                                            :surname => user["LastName"],
                                                            :given_name => user["FirstName"]) 
                    contributor.update_attributes(:user_id => @user.id) if (user["ID"].to_s == @user.mas)
                  end
                  Work.delay.update_via_crossref(work)
                end
              end
            end
          end
        elsif params[:service] == "twitter"
          TwitterService.delay.update_via_twitter(@user)
        end
        format.html { render :show }
        format.js { render :show }
        format.xml  { head :ok }
        format.json { head :ok }
      else  
        format.js { render :show }

app/views/users/_book_content.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<% unless @user.book_contents.empty? %>
	<% @user.book_contents.each do |@work| %>
	  <div class="row" id="work_<%= @work.id %>">
		  <%= render :partial => "works/work" %>
	  </div>
  <% end %>	
<% else %>
	<div class="alert alert-info">
		No book chapters found.
  </div>
<% end %>
<br />

app/views/users/_form.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<% user ||= form %>
<%= form_for(user) do |f| %>
  <p>
    <%= f.label :mas, "Author ID" %><br />
    <%= f.text_field :mas %>
  </p>
  <p>
    <%= f.submit(user.new_record? ? "Create" : "Update") %>
  </p>
<% end %>

app/views/users/_friend.html.erb
<% unless @user.friends.empty? %>
	<% @user.friends.each do |friend| %>
	  <div class="row">
		  <div class="span1">
			  <%= image_tag "http://api.twitter.com/1/users/profile_image/#{friend.username}", :class => "photo_works" %>
			</div>
		  <div class="span8 work">
				<h4><%= link_to friend.display_name, user_path(friend.username) %></h4>
	      <p><%= link_to "@#{friend.username}", "http://twitter.com/#{friend.username}" %>
		    <br />
				<% unless friend.description.blank? %>
					<%= friend.description %>
				<% end %>
				</p>
	    </div>
	  </div>
  <% end %>	
<% else %>
	<div class="alert alert-info">
		No friends found.
  </div>
<% end %>
<br />

app/views/users/_index.html.erb
<div class="content">	
  <% unless @works.empty? %>
		<% @works.each do |@work| %>
			<div class="row" id="work_<%= @work.id %>">
				<%= render :partial => "works/work" %>
		  </div>
    <% end %>
    <div class="row">
	    <div class="span9">
		    <%= will_paginate @works, :params => { :controller => :works, :authenticity_token => nil } %>
		  </div>
		</div>
  <% else %>
    <div class="alert alert-info">
      No works found.
	  </div>
  <% end %>
</div>

app/views/users/_journal_article.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>

<% unless @user.journal_articles.empty? %>
	<% @user.journal_articles.each do |@work| %>
	  <div class="row" id="work_<%= @work.id %>">
		  <%= render :partial => "works/work" %>
	  </div>
  <% end %>	
<% else %>
	<div class="alert alert-info">
		No journal articles found.
  </div>
<% end %>
<br />

app/views/users/_service.html.erb
<% unless (controller.action_name == "edit" or (controller.action_name == "update" and !@user.errors.empty?)) and ["mas", "mendeley", "authorclaim", "scopus", "googlescholar"].include?(params[:service]) %>

  <ul class="thumbnails">
	
		<% if !@user.mas.blank? or current_user == @user or current_user.try(:admin?) %>
		  <li class="span3">
	      <div class="thumbnail">
			    <%= image_tag "mas.png", :class => "photo_mini", :title => "Microsoft Academic Search" %>
				  <div class="service"><%= @user.mas.blank? ? "not set" : link_to(@user.mas, "http://academic.research.microsoft.com/Author/" + @user.mas) %>
				  	<% if current_user == @user or current_user.try(:admin?) %>&nbsp;<%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(@user.username, :partial => "service", :service => "mas"),
						                                     :remote => true,
					                                       :method => :get,
					                                       :title => "Edit Microsoft Academic Search" %>
					 <% end %>
				 </div>
			 </div>
			</li>
		<% end %>
		
		<% if !@user.authorclaim.blank? or current_user == @user or current_user.try(:admin?) %>
			<li class="span3">
	      <div class="thumbnail">
			    <%= image_tag "authorclaim.png", :class => "photo_mini", :title => "AuthorClaim" %>
					<div class="service"><%= @user.authorclaim.blank? ? "not set" : link_to(@user.authorclaim, "http://authorclaim.org/profile/" + @user.authorclaim) %>
					<% if current_user == @user or current_user.try(:admin?) %>&nbsp;<%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(@user.username, :partial => "service", :service => "authorclaim"),
					                                       :remote => true,
																								 :method => :get,
					                                       :title => "Edit AuthorClaim" %>
					<% end %>
					</div>
				</div>
			</li>
		<% end %>
		
		<% if !@user.mendeley.blank? or current_user == @user or current_user.try(:admin?) %>
		  <li class="span3">
        <div class="thumbnail">
			  	<%= image_tag "mendeley.png", :class => "photo_mini", :title => "Mendeley" %>
					<div class="service"><%= @user.mendeley.blank? ? "not set" : link_to(@user.mendeley, "http://www.mendeley.com/profiles/" + @user.mendeley) %>
					<% if current_user == @user or current_user.try(:admin?) %>&nbsp;<%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(@user.username, :partial => "service", :service => "mendeley"),
					                                       :remote => true,
																								 :method => :get,
					                                       :title => "Edit Mendeley" %>
					<% end %>
					</div>
			  </div>
		  </li>
		<% end %>

		<% if !@user.googlescholar.blank? or current_user == @user or current_user.try(:admin?) %>
	    <li class="span3">
        <div class="thumbnail">
					<%= image_tag "googlescholar.png", :class => "photo_mini", :title => "Google Scholar" %>
					<div class="service"><%= @user.googlescholar.blank? ? "not set" : link_to(@user.googlescholar, "http://scholar.google.com/citations?user=" + @user.googlescholar) %>
						<% if current_user == @user or current_user.try(:admin?) %>&nbsp;<%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(@user.username, :partial => "service", :service => "googlescholar"),
						                                       :remote => true,
																									 :method => :get,
						                                       :title => "Edit Google Scholar" %>
						<% end %>
					</div>
	      </div>
	    </li>
		<% end %>
  </ul>
<% else %>
  <div class="row">
	  <div class="span8">
		  <% if params[:service] == "mas" %>
		    <%= form_for :user, :url => user_path(@user.username, :partial => "service", :service => "mas"), :html => { :class => "well", :method => :put, :remote => true } do |f| %>
			  <label>Microsoft Academic Search</label>
		      <% if mas_choices(@user).nil? or mas_choices(@user).empty? %>
		        <%= f.text_field :mas %>
		      <% else %>
		        <%= f.select(:mas, mas_choices(@user), { :include_blank => 'None', :prompt => 'Please Select:' }, { :class => 'span7' }) %>
		      <% end %>
			  <p class="help-block">The names are pulled from Microsoft Academic Search based on the name in your profile.</p>
		      <br />
		      <%= f.submit("Submit", :class => "btn-primary btn-mini") %>
		      <%= link_to "Cancel", user_path(@user.username, :partial => "service"), :remote => true %>
				<% end %>
		  <% elsif params[:service] == "authorclaim" %>
		    <%= form_for :user, :url => user_path(@user.username, :partial => "service", :service => "authorclaim"), :html => { :class => "well", :method => :put, :remote => true } do |f| %>
				    <label>AuthorClaim</label>
				  <div class="input-prepend">
				  	<span class="add-on">http://authorclaim.org/profile/</span><%= f.text_field :authorclaim %>
				  </div>
				  <p class="help-block">This is the user-specific component of your "Permanent URL", which can also be found as your "Short-id" when logged in on the profile overview page.</p>
				  <br />
				  <%= f.submit("Submit", :class => "btn-primary btn-mini") %>
				  <%= link_to "Cancel", user_path(@user.username, :partial => "service"), :remote => true %>
				<% end %>
		  <% elsif params[:service] == "mendeley" %>
		    <%= form_for :user, :url => user_path(@user.username, :partial => "service", :service => "mendeley"), :html => { :class => "well", :method => :put, :remote => true } do |f| %>
		      <label>Mendeley</label>
				  <div class="input-prepend">
				  	<span class="add-on">http://www.mendeley.com/profiles/</span><%= f.text_field :mendeley %>
				  </div>
				  <p class="help-block">This is the user-specific component of your Mendeley profile URL.</p>
				  <br />
				  <%= f.submit("Submit", :class => "btn-primary btn-mini") %>
				  <%= link_to "Cancel", user_path(@user.username, :partial => "service"), :remote => true %>
			  <% end %>
		  <% elsif params[:service] == "googlescholar" %>
		    <%= form_for :user, :url => user_path(@user.username, :partial => "service", :service => "googlescholar"), :html => { :class => "well", :method => :put, :remote => true } do |f| %>
		      <label>Google Scholar</label>
			  <div class="input-prepend input-append">
			    <span class="add-on">http://scholar.google.com/citations?user=</span><%= f.text_field :googlescholar %>
			  </div>
			  <p class="help-block">This is the user-specific component of your Google Scholar profile URL.</p>
			  <br />
			  <%= f.submit("Submit", :class => "btn-primary btn-mini") %>
			  <%= link_to "Cancel", user_path(@user.username, :partial => "service"), :remote => true %>
			<% end %>
		  <% end %>
		</div>
	</div>
<% end %>

app/views/users/_show.html.erb
<div class="content">
	<div class="row">
		<% unless @user.image.blank? %>
	    <div class="span2" id="photo">
		    <%= image_tag @user.image, :class => "photo" %>
			</div>
			<div class="span6" id="twitter">
		<% else %>
		  <div class="span6 offset2" id="twitter">
		<% end %>
		  <%= render :partial => 'twitter' %>
		</div>
		<div class="span3 offset1">
			<p><%= link_to "JSON", user_path(@user.username, :format => :json) %> | <%= link_to "XML", user_path(@user.username, :format => :xml) %> | <%= link_to "BibTeX", user_path(@user.username, :format => :bib) %> | <%= link_to "RIS", user_path(@user.username, :format => :ris) %> | <%= link_to "CSV", user_path(@user.username, :format => :csv) %></p>
		</div>
	</div>
	
	<ul class="nav nav-tabs">
		<li class="<%= @user.has_profile ? '' : 'active' %>"><a href="#service" data-toggle="tab">Identifiers</a></li>
		<% if @user.has_profile %>
		<li class="active"><a href="#source" data-toggle="tab">Metrics</a></li>
		<% unless @user.journal_articles.empty? %>
		  <li><a href="#journal_article" data-toggle="tab">Journal Articles (<%= @user.journal_articles.count %>)</a></li>
		<% end %>
		<% unless @user.conference_papers.empty? %>
		  <li><a href="#conference_paper" data-toggle="tab">Conference Papers (<%= @user.conference_papers.count %>)</a></li>
		<% end %>
		<% unless @user.book_contents.empty? %>
		  <li><a href="#book_content" data-toggle="tab">Book Chapters (<%= @user.book_contents.count %>)</a></li>
		<% end %>
		<% unless @user.friends.empty? %>
		  <li><a href="#friend" data-toggle="tab">Friends (<%= @user.friends.count %>)</a></li>
		<% end %>
		<% end %>
	</ul>	
	
	<div class="tab-content">
		<div class="tab-pane <%= @user.has_profile ? '' : 'active' %>" id="service">
			<%= render :partial => 'service' %>
		</div>
		
		<% if @user.has_profile %>
			<div class="tab-pane active" id="source">
			  <%= render :partial => 'source'%>
			</div>

			<div class="tab-pane" id="journal_article">
			  <%= render :partial => 'journal_article' %>
			</div>
			
			<div class="tab-pane" id="conference_paper">
			  <%= render :partial => 'conference_paper' %>
			</div>
			
			<div class="tab-pane" id="book_content">
			  <%= render :partial => 'book_content' %>
			</div>
			
			<div class="tab-pane" id="friend">
			  <%= render :partial => 'friend' %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/_twitter.html.erb
<% if params[:partial] == "twitter" and ((controller.action_name == "edit" or (controller.action_name == "update" and !@user.errors.empty?))) %>
	<%= form_for :user, :url => user_path(@user.username, :partial => "twitter", :service => "twitter"), :html => { :class => "well", :method => :put, :remote => true } do |f| %>
	  <label>Name</label>
	  <%= f.text_field :name %><br />
	  <%= f.submit("Submit", :class => "btn-primary btn-mini") %>
	  <%= link_to "Cancel", user_path(@user.username, :partial => "twitter"), :remote => true %>
	<% end %>
<% else %>
	<h2>
		<%= h(@user.display_name) %>
		<% if current_user == @user or current_user.try(:admin?) %>
			<small><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(@user.username, :partial => "twitter"), :remote => true, :title => "Edit Name" %></small>
		<% end %>
	</h2>
  <h4><%= link_to "@#{@user.username}", "http://twitter.com/" + @user.username %></h4>
	<% unless @user.location.blank? %>
		<%= @user.location %>
	<% end %>
	<p>
	<% unless @user.description.blank? %>
		<%= @user.description %><br/>
	<% end %>
	<% unless @user.website.blank? %>
		<%= link_to @user.website, @user.website %>
	<% end %>
<% end %>

app/views/users/_work.mobile.erb
<% unless @user.works.empty? %>
  <% unless active_categories.empty? %>
    <div data-role="collapsible" data-collapsed="false">
	    <h3>Metrics</h3>
      <%= render :partial => 'source'%>
    </div>
  <% end %>
  
  <div data-role="collapsible">
	  <h3 class="show">Works</h3>
    <ul data-role="listview" data-theme="c" data-filter="true" data-filter-placeholder="Filter works...">
      <% @user.works.each do |work| %>
	      <li><a href="<%= work_path(work.id) %>" class="normal">
          <h3><%= work.title %></h3>
          <%= formatted_citation(work, :without_links => true).html_safe %>
          </a>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<div data-role="collapsible">
  <h3 class="show">Friends</h3>
	<ul data-role="listview" data-theme="c" data-filter="true" data-filter-placeholder="Filter friends...">
		<% @user.friends.each do |user| %>
			<li><a href="<%= user_path(user.username) %>" class="signed_in">
		    <%= image_tag "http://api.twitter.com/1/users/profile_image/#{user.username}" %>
			  <h3><%= "#{user.display_name}" %></h3>
			  <%= "@#{user.username}" %>
			  </a>
			</li>
	  <% end %>
	</ul>
</div>

<% if @user.has_profile and !@user.works.empty? %>
	</div>
<% end %>

app/views/users/edit.html.erb
<%#
  # Copyright (c) 2011 Martin Fenner
  #
  # Licensed under the Apache License, Version 2.0 (the "License");
  # you may not use this file except in compliance with the License.
  # You may obtain a copy of the License at
  #
  #     http://www.apache.org/licenses/LICENSE-2.0
  #
  # Unless required by applicable law or agreed to in writing, software
  # distributed under the License is distributed on an "AS IS" BASIS,
  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  # See the License for the specific language governing permissions and
  # limitations under the License.
-%>
<div class="border">
<div class="page">
  <h1>Editing user <%=h @user.mas %></h1>

  <%= render :partial => "form", :object => @user %>

  <%= link_to 'Show', @user %>
  <br/>
  <%= link_to 'Back to list', users_path %>
</div>
</div>