config/routes.rb
# Copyright (c) 2009-2010 by Public Library of Science, a non-profit corporation
# http://www.plos.org/
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

PlosAltMetrics::Application.routes.draw do
  root :to => "users#index"
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_scope :users do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
    get 'sign_in', :to => 'users/sessions#new', :as => :new_users_session
    match 'sign_out', :to => 'users/sessions#destroy', :as => :destroy_user_session, :via => [:get, :delete]
  end
  
  resources :works do
    resources :likes, :comments
  end
  
  resources :articles
  #match "/group/articles(/:id)(.:format)" => "groups#groupArticleSummaries"
  
  resources :groups
  resources :journals
  resources :books
  
  # Admin resources
  resources :sources
  resources :categories
  resources :authentications
  get '/docs(/:action)', :controller => :docs, :format => false
  get 'about', :to => 'index#index', :as => "about"
  
  # Authors are in default path, should therefore be defined after admin resources. 
  # Root goes to works#index, needs to be defined.
  resources :users, :path => "/"

end

app/views/layouts/application.html.erb
<%# Copyright (c) 2011 Martin Fenner
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
-%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>
      <%= "(#{Rails.env}) " unless Rails.env.production? %>
      <%= APP_CONFIG['application'] %>
    </title>
    <link rel="shortcut icon" href="/favicon.ico">
		<!--[if lt IE 9]>
		  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<%= stylesheet_link_tag :application %>
		<%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
	</head>
  <body>
	  <div class="navbar navbar-fixed-top">
		  <div class="navbar-inner">
				<div class="container">
				  <a class="brand" href="<%= root_path %>"><%= APP_CONFIG['application'] %></a>
				  <%= render_navigation %>
				  <% if ["works", "users", "groups", "journals", "books"].include?(controller.controller_name) and ["index"].include?(controller.action_name) %>
			      <%= form_tag({:controller => controller.controller_name, :action => "index"}, :method => "get", :class => "navbar-search pull-left") do %>
			        <%= search_field_tag :q, params[:q], :placeholder => "Search", :class => "search-query" %>
			      <% end %>
			    <% end %>
					<ul class="nav pull-right">
					  <% if current_user.try(:admin?) %>
							<li class="dropdown">
							  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Administration <b class="caret"></b></a>
						    <ul class="dropdown-menu">
					        <li><%= link_to '<i class="icon-inbox"></i> Sources'.html_safe, sources_path %></li>
						      <li><%= link_to '<i class="icon-list-alt"></i> Categories'.html_safe, categories_path %></li>
						      <% if controller.controller_name == "users" and controller.action_name == "show" %>
									  <li class="divider"></li>
			   	          <li><%= link_to '<i class="icon-pencil"></i> Edit User'.html_safe, edit_user_path(@user, :partial => "twitter"), :remote => true %></li>
			              <li><%= link_to '<i class="icon-refresh"></i> Refresh'.html_safe, user_path(@user.username, :refresh => "now"), :remote => true %></li>
										<% elsif controller.controller_name == "works" and controller.action_name == "show" %>
										  <li class="divider"></li>
				              <li><%= link_to '<i class="icon-refresh"></i> Refresh'.html_safe, work_path(@work.short_doi, :refresh => "now"), :remote => true %></li>
						      <% elsif controller.controller_name == "sources" and controller.action_name == "show" %>
				            <li class="divider"></li>
				   	        <li><%= link_to '<i class="icon-pencil"></i> Edit Source'.html_safe, edit_source_path(@source) %></li>
				          <% elsif controller.controller_name == "categories" %>
			         	    <li class="divider"></li>
				            <% if controller.action_name == "index" %>
				              <li><%= link_to 'New Category', new_category_path %></li>
				            <% elsif controller.action_name == "show" %>
				              <li><%= link_to '<i class="icon-pencil"></i> Edit Category'.html_safe, edit_category_path(@category) %></li>
				            <% end %>
				          <% end %>
						    </ul>
						  </li>
						<% end %>
						<% if user_signed_in? %>
							<li class="dropdown">
						    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.name %> <%= image_tag "http://api.twitter.com/1/users/profile_image/#{current_user.username}", :class => "photo_nav" %> <b class="caret"></b></a>
					      <ul class="dropdown-menu">
			            <li><%= link_to '<i class="icon-user"></i> Your Card'.html_safe, user_path(current_user.username) %></li>
			            <li class="divider"></li>
			   	        <li><%= link_to '<i class="icon-off"></i> Sign Out'.html_safe, destroy_user_session_path, :method => :delete %></li>
			          </ul>
			        </li>
			      <% else %>
							<li><%= link_to "Sign In with Twitter", user_omniauth_authorize_path(:twitter) %></li>
			      <% end %>
		      </ul>
				</div>
			</div>
		</div>

		<div class="container">
		  <% [ :error, :notice, :warning, :message ].each do |name| %>
		    <% if flash[name] %>
		      <div class="alert alert-success">
		        <%= flash[name] %>
	        </div>
			  <% end %>
		  <% end %>
		  <%= yield %>
			<footer>
	      an <%= link_to image_tag("altmetrics.png"), "http://www.altmetrics.org" %> project.
			</footer>
	  </div>
	</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>
	    <%= "(#{Rails.env}) " unless Rails.env.production? %>
	    <%= APP_CONFIG['application'] %>
	  </title>
	  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
	  <%= stylesheet_link_tag 'http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.css' %>
	  <%= stylesheet_link_tag :mobile %>
		<%= javascript_include_tag :application %>
	  <%= javascript_include_tag "http://code.jquery.com/mobile/1.0/jquery.mobile-1.0.js" %>
	  <%= csrf_meta_tag %>
	</head>
	<body>
		<div data-role="page" data-theme="b" id="<%= controller.controller_name %>">
		  <%= yield %>
		</div>
	</body>
</html>